spring.application.name=finanzas

# =============================================
# BASE DE DATOS — R2DBC PostgreSQL
# =============================================
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/finanzas_db
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.max-life-time=1h

logging.level.com.finanzas.personales.finanzas.config.SqlQueryLoader=DEBUG

# =============================================
# JWT
# =============================================
app.jwt.secret=clave-secreta-finanzas-personales-2026-cambiar-en-produccion
app.jwt.expiration-ms=86400000

# =============================================
# CORS
# =============================================
app.cors.allowed-origins=*

# =============================================
# WEBFLUX
# =============================================
spring.webflux.base-path=/
server.port=9000
server.address=0.0.0.0

# =============================================
# SPRINGDOC — Swagger UI / OpenAPI
# =============================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
